### PR TITLE
Allow pasting lists in tables

### PR DESCRIPTION
**Pull request by Jacfem**
In response to [QA Verification note](https://docs.google.com/spreadsheets/d/1PsP4iBxM6gXUxtqyKGtBUeDYE6wkqWQwLYeicwDHzfM/edit#gid=0) here: https://www.loom.com/share/b0f78e3c6bd84561a96fce9294b8ace3

Functionality: https://www.loom.com/share/1fb98c18c91b4194b0f1e4516f90075e

### CODE REVIEW

**Comment by ivanaveliskova** [comment]
Hmm that extra space at the beginning might get annoying  to users? I  wonder if there is some way to remove that, like do  a remove  the node and replace it with the list? or place the list inside the paragraph node in the table?

**Comment by Jacfem** [comment]
Oooh good eye, I didn't notice that. Yeah I'm sure there's some way around that, will investigate 👍

**Review by ivanaveliskova — APPROVED** [review]

**Comment by ivanaveliskova** [comment]
Either way this is  an  awesome find!

**Comment by YurkaninRyan** [comment]
Are we going to run into normalizer errors with this?  Are there any rules that don't allow for anything other than text and inlines to be in a table cell?

**Comment by Jacfem** [comment]
@YurkaninRyan thanks for the question -- @ivanaveliskova can probably speak more to that, but lists are now supported in tables with our upgrade, which is why we wanted to upgrade this pasting functionality. I would assume I would see an error when trying to do this if there was something the normalizer didn't like about it, is that incorrect?

**Comment by ivanaveliskova** [comment]
@YurkaninRyan From reading the schema code, currently, table cells will allow onlyBlocksInCells, and inlines that specifically go inside the blocks. The block that specifically goes in is a paragraph from my understanding, so I think any blocks that are allowed inside of paragraphs would appear.

**Comment by Jacfem** [comment]
_Oh_ also, I'm going to add a cypress test case for lists in tables to our Guru-UI PR once we have this in

**Comment by ivanaveliskova** [comment]
@Jacfem if you have this pulled up locally, could you test out what would happen if you copied some test that had like an iframe in it, or a `<hr>` something out of the ordinary. I personally think allowing something like a heading inside the table shouldn't be a problem, but I think since we don't currently allow iframes/dividers/code blocks/etc we should be wary. I know you can write three backticks in a cell and it will create a code block so we might need to go in and make some modifications for that

**Comment by Jacfem** [comment]
Yep, good suggestion @ivanaveliskova, I'll run through pasting all our other blocks that I can find into a table cell and report back

**Comment by Jacfem** [comment]
Ok here's what I found -- Ivana mentioned we might be able to update the schema to only allow paragraphs and lists?
- Copying and pasting headers inserts it with the header styling
- Dividers paste below
- Inserting a video or iframe inserts it below
- Copying and pasting a Video + IFrame attempts to paste and only inserts an empty line (I want to investigate this more)
- Link pastes within
- Guru card pastes within
- Preview block pastes within


Edit - An alternative to my code here would be that we try to match the existing production behavior, which is that it pastes the list within the cell but strips the actual list formatting, so you just get the lines of text

**Comment by Jacfem** [comment]
Ok, one other option I wanted to throw out there for feedback: we could add a condition in here that only allows lists to be pasted, and otherwise we again return null which is the existing behavior -- so we have `fragment` available to us, and we know that its nodes type is a bulleted_list -- could we restrict this to only bulleted or numbered lists? Forgive me if this is something that belongs elsewhere, still wrapping my head around what piece should be responsible for what!

**Comment by Jacfem** [comment]
Closing, we are deferring fully formatted list pasting to its own dedicated follow-up feature.

**Pull request closed without merging**
